export interface Template {
  id: string
  url: string
  name: string
  category: string
  description: string
}

// Mock template images - using placeholder images for now
// In production, these would be actual template images stored in your CDN
export const mockTemplates: Template[] = [
  {
    id: "template-1",
    url: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&h=400&fit=crop",
    name: "Business Portrait",
    category: "Professional",
    description: "Professional business portrait template"
  },
  {
    id: "template-2", 
    url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop",
    name: "Casual Outdoor",
    category: "Lifestyle",
    description: "Casual outdoor portrait with natural lighting"
  },
  {
    id: "template-3",
    url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=400&fit=crop",
    name: "Fashion Studio",
    category: "Fashion",
    description: "High fashion studio portrait"
  },
  {
    id: "template-4",
    url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop",
    name: "Natural Beauty",
    category: "Beauty",
    description: "Natural beauty portrait with soft lighting"
  },
  {
    id: "template-5",
    url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop",
    name: "Artistic Portrait",
    category: "Artistic",
    description: "Creative artistic portrait"
  },
  {
    id: "template-6",
    url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop",
    name: "Corporate Headshot",
    category: "Professional",
    description: "Corporate headshot for LinkedIn"
  },
  {
    id: "template-7",
    url: "https://images.unsplash.com/photo-1521119989659-a83eee488004?w=400&h=400&fit=crop",
    name: "Street Style",
    category: "Lifestyle",
    description: "Urban street style portrait"
  },
  {
    id: "template-8",
    url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop",
    name: "Glamour Shot",
    category: "Fashion",
    description: "Glamour photography portrait"
  },
  {
    id: "template-9",
    url: "https://images.unsplash.com/photo-1488161628813-04466f872be2?w=400&h=400&fit=crop",
    name: "Adventure Portrait",
    category: "Lifestyle",
    description: "Outdoor adventure portrait"
  },
  {
    id: "template-10",
    url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop",
    name: "Soft Portrait",
    category: "Beauty",
    description: "Soft lighting beauty portrait"
  },
  {
    id: "template-11",
    url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop",
    name: "Formal Portrait",
    category: "Professional",
    description: "Formal professional portrait"
  },
  {
    id: "template-12",
    url: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=400&fit=crop",
    name: "Editorial",
    category: "Fashion",
    description: "Editorial fashion portrait"
  }
]

// Mock results for demo purposes
// In production, these would be generated by the AI model
export const getMockSwapResult = (templateId: string, characterRef: string): string => {
  // For demo, we'll return a different placeholder image as the "result"
  const resultImages = [
    "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop",
    "https://images.unsplash.com/photo-1504593811423-6dd665756598?w=400&h=400&fit=crop",
    "https://images.unsplash.com/photo-1555952517-2e8e729e0b44?w=400&h=400&fit=crop",
    "https://images.unsplash.com/photo-1463453091185-61582044d556?w=400&h=400&fit=crop",
  ]
  
  // Generate a deterministic index based on template and character
  const hash = templateId.length + characterRef.length
  const index = hash % resultImages.length
  
  return resultImages[index]
}

// Mock inpaint result
export const getMockInpaintResult = (
  templateId: string, 
  characterRef: string,
  maskData: string
): string => {
  // For demo, return a different result based on mask presence
  const inpaintResults = [
    "https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=400&h=400&fit=crop",
    "https://images.unsplash.com/photo-1507081323647-4d250478b919?w=400&h=400&fit=crop",
    "https://images.unsplash.com/photo-1502323777036-f29e3972d82f?w=400&h=400&fit=crop",
    "https://images.unsplash.com/photo-1514315384763-ba401779410f?w=400&h=400&fit=crop",
  ]
  
  const hash = templateId.length + characterRef.length + maskData.length
  const index = hash % inpaintResults.length
  
  return inpaintResults[index]
}
